version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: yarn start