version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: yarn start